//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KurssiToteutukset
    {
        public string Kurssi { get; set; }
        public Nullable<System.DateTime> Paivamaara { get; set; }
        public Nullable<int> Opettaja { get; set; }
        public Nullable<int> Luokka { get; set; }
        public Nullable<int> KurssiId { get; set; }
    
        public virtual Kurssit Kurssit { get; set; }
        public virtual Luokkatilat Luokkatilat { get; set; }
    }
}
