//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum3.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KurssiToteutukset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KurssiToteutukset()
        {
            this.Osallistumiset = new HashSet<Osallistumiset>();
        }
    
        public int KurssitoteutusID { get; set; }
        [Display(Name = "P‰iv‰m‰‰r‰")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable <System.DateTime> Paivamaara { get; set; }
        public int Opettaja { get; set; }
        public int Luokka { get; set; }
        public int Kurssi { get; set; }
        public System.TimeSpan Kellonaika { get; set; }
    
        public virtual Kurssit Kurssit { get; set; }
        public virtual Luokkatilat Luokkatilat { get; set; }
        public virtual Opettajat Opettajat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Osallistumiset> Osallistumiset { get; set; }
    }
}
