//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osallistumiset
    {
        public int ID { get; set; }
        public int Oppilas { get; set; }
        public string Osallistuminen { get; set; }
        public Nullable<int> Arvosana { get; set; }
    
        public virtual Kurssit Kurssit { get; set; }
        public virtual Opiskelijat Opiskelijat { get; set; }
    }
}
