//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum3.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Osallistumiset
    {
        [Display(Name = "Kurssitoteutus")]
        public int OsallistumisetID { get; set; }
        [Display(Name = "Kurssitoteutus")]
        public int KurssitoteutusID { get; set; }
        [Display(Name = "Oppilas")]
        public int OppilasID { get; set; }
        [Display(Name = "P‰iv‰m‰‰r‰")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Paivamaara { get; set; }


        public virtual KurssiToteutukset KurssiToteutukset { get; set; }
        public virtual Opiskelijat Opiskelijat { get; set; }
    }
}
