//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum3.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScrumEntities : DbContext
    {
        public ScrumEntities()
            : base("name=ScrumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kurssit> Kurssit { get; set; }
        public virtual DbSet<KurssiToteutukset> KurssiToteutukset { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<Luokkatilat> Luokkatilat { get; set; }
        public virtual DbSet<Opettajat> Opettajat { get; set; }
        public virtual DbSet<Opiskelijat> Opiskelijat { get; set; }
        public virtual DbSet<Osallistumiset> Osallistumiset { get; set; }
        public virtual DbSet<PaaKayttajat> PaaKayttajat { get; set; }
    }
}
